package com.crypto.cryptosim.structures;

public enum Info {

    // Après l'inscription
    SIGNUP_ACCOUNT_CREATED,

    //
    DEPOSIT_DONE,
    WITHDRAWAL_DONE,

    PASSUPDATE_SUCCESS,

    ACCDELETION_SUCCESS,

    SUPPORTREQUEST_SUCCESS,
    SUPPORTRESPONSE_SUCCESS,

    WALLET_CREATED,
    WALLET_TRANSACTION_DONE,
    WALLET_DEPOSIT_DONE,
    WALLET_WITHDRAWAL_DONE
}
